FROM node:14.16-alpine as react
ENV PATH="/application/node_modules/.bin:${PATH}"

WORKDIR /application
COPY ./package.json ./package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM nginx:alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react /application/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]