version: '3.8'

networks:
  shared-services:
    driver: bridge
    name: shared-services

volumes:
  mongo:

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - mongo:/data/db
    networks:
      - shared-services
